# Copyright (c) 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# - Philippe Sauter <phsauter@iis.ee.ethz.ch>

services:
  pulp-docker:
    image: hpretl/iic-osic-tools:2025.03
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - ./:/fosic/designs/croc
    stdin_open: true
    tty: true
    working_dir: /fosic/designs/croc
    entrypoint: /dockerstartup/scripts/ui_startup.sh
    command: --skip bash
    # Resource allocation
    #deploy:
      #resources:
        #limits:
          #cpus: '8.0'       # Allow access to up to 8 CPU cores
          #memory: 12288M     # Limit memory to 8192 MB (8 GB)
        # reservations: # Optional: guarantee resources if needed, usually for production
        #   cpus: '4.0'
        #   memory: 4096M
    # For older Docker Compose versions or non-swarm mode, these might be direct keys:
    # cpus: '8.0' # Or just 8 depending on Docker version/setup
    # mem_limit: 8192m # Or '8g'

    
