// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtb_obi_spi_direct.cpp"
#include "Vtb_obi_spi_direct___024root__DepSet_h4f1d96ef__0.cpp"
#include "Vtb_obi_spi_direct___024root__DepSet_h562ebb3d__0.cpp"
#include "Vtb_obi_spi_direct__main.cpp"
#include "Vtb_obi_spi_direct__Trace__0.cpp"
#include "Vtb_obi_spi_direct___024root__Slow.cpp"
#include "Vtb_obi_spi_direct___024root__DepSet_h4f1d96ef__0__Slow.cpp"
#include "Vtb_obi_spi_direct___024root__DepSet_h562ebb3d__0__Slow.cpp"
#include "Vtb_obi_spi_direct__Syms.cpp"
#include "Vtb_obi_spi_direct__Trace__0__Slow.cpp"
#include "Vtb_obi_spi_direct__TraceDecls__0__Slow.cpp"
